# Generated by Django 4.0.4 on 2022-06-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0003_customuser_recently_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='recently_viewed',
        ),
    ]
