# Generated by Django 4.0.4 on 2022-05-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='product',
            new_name='blog',
        ),
    ]
