# Generated by Django 4.0.4 on 2022-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preview_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
