# Generated by Django 4.0.4 on 2022-05-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_preview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='preview_title',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
