# Generated by Django 4.0.4 on 2022-05-06 12:45

from django.db import migrations, models
import django.db.models.deletion
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_text', models.TextField()),
                ('full_hd_image', models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path)),
                ('preview_photo', models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path)),
                ('available', models.IntegerField(blank=True, null=True)),
                ('sold', models.IntegerField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('product_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('old_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('trends', models.BooleanField(blank=True, null=True)),
                ('new', models.BooleanField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='home.category')),
            ],
            options={
                'verbose_name_plural': 'Product',
                'ordering': ('is_active',),
            },
        ),
        migrations.CreateModel(
            name='Top_seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=home.models.user_directory_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.product')),
            ],
        ),
    ]
