# Generated by Django 4.0.4 on 2022-05-08 18:51

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('is_active',), 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='full_hd_image',
            field=models.ImageField(null=True, upload_to=home.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Normal Cost'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_photo',
            field=models.ImageField(null=True, upload_to=home.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Discount cost'),
        ),
    ]
