# Generated by Django 4.0.4 on 2022-05-28 11:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0009_alter_product_is_faivorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_faivorite',
            field=models.ManyToManyField(blank=True, default=None, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
